### ISSUE TITLE
Add button to align zero on all plots and autoscale to largest one

### ISSUE THREAD

**Issue by Hwurzburg** [Williangalvani/UAVLogViewer#184]
this wont help much in mixed plots, but I have been running a lot of rangefinder tests which compare three alts and this would have saved me soooo much time aligning and scaling everything so that they are the same...even then the scale granularity would not allow me to perfectly align the three altitude plots...baro, rangefinder, rangefinder target....this would be great for checking attitudes , pids, etc. also...and if you had to have mixed graphs, it would be nice if the scales/zeros of the previously aligned graphs do not get adjusted when you add new non-homogenous plots...and it would screw up plots that dont have zero, but the user would just have to be cautious in pushing the button

**Comment by Williangalvani** [comment]
So you need the same zeros but different scales? One alternative (not great) would be to just multiply some of them and use the same axis

**Comment by Hwurzburg** [comment]
no same zeros....same scales...
![f-4_g2](https://user-images.githubusercontent.com/6076534/84654115-3d1f9080-aed4-11ea-88af-e66e833410b0.png)

**Comment by Williangalvani** [comment]
the dropdown menu with a number selects with "axis" the plot is at. In this last example you could put all plots at axis 0:
![Screenshot from 2020-06-15 11-44-16](https://user-images.githubusercontent.com/4013804/84671311-9a7c0780-aefd-11ea-9bc9-d253cb970db7.png)

**Comment by Hwurzburg** [comment]
brilliant!...this really needs a wiki!
